### ISSUE TITLE
Crashing when adding an item/block that isn't meant for the campfire

### ISSUE THREAD

**Issue by K-Proj** [spacegoat3/ConfigurableRecipes#7]
The Client seems to crash every time a player uses any item that is not:
Coal, Charcoal, and Soul Sand (maybe others are fine to).

To test if it wasn't a conflict with another mod, a fresh modpack was created, with only campfire and REI.
Still the client crashed when a player used a wrong item to continue building the campfire past the 4 logs block state, such as a vanilla stone block.

The crash report goes as follows:
Description: Unexpected error
```
java.lang.NoClassDefFoundError: potionstudios/byg/common/item/BYGItems
	at net.spacegoat.buildable_campfire.CampfireLogBlock.method_9534(CampfireLogBlock.java:153)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939)
	at net.minecraft.class_636.method_2896(class_636.java:320)
	at net.minecraft.class_310.method_1583(class_310.java:1659)
	at net.minecraft.class_310.method_1508(class_310.java:1912)
	at net.minecraft.class_310.method_1574(class_310.java:1739)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: potionstudios.byg.common.item.BYGItems
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 12 more
```
Outside of this, it's been a nice surprise to see how well it works with so many other campfire mods. Great stuff!

**Comment by K-Proj** [comment]
I also just realized this issue tracker is for another project, NOT Building campfire, but the link on curseforge for the issue tracker sends people here, so I'll leave it here just in-case this is still the preferable place for reporting bugs.

**Comment by spacegoat3** [comment]
A similar issue was reported this week. I am trying to fix it. Thanks for letting me know though.
